export interface MathSnippet {
  kind: 'fraction' | 'sqrt' | 'power' | 'subscript' | 'powerSubscript' | 'brackets' | 'matrix'
  value: string
  title: string
  selectText?: string
}

export interface MathSymbol {
  label: string
  value: string
  title: string
}

export type MathInputPanel = 'structure' | 'operator' | 'relation' | 'letter' | 'set' | 'common'

export interface MathPanelTab {
  id: MathInputPanel
  label: string
}

export const MATH_STRUCTURE_SNIPPETS: MathSnippet[] = [
  { kind: 'fraction', value: '\\frac{a}{b}', title: '插入分数', selectText: 'a' },
  { kind: 'sqrt', value: '\\sqrt{x}', title: '插入根号', selectText: 'x' },
  { kind: 'power', value: 'x^{2}', title: '插入上标', selectText: '2' },
  { kind: 'subscript', value: 'x_{1}', title: '插入下标', selectText: '1' },
  { kind: 'powerSubscript', value: 'x_{1}^{2}', title: '插入上下标', selectText: '1' },
  { kind: 'brackets', value: '\\left( x \\right)', title: '插入括号', selectText: 'x' },
  {
    kind: 'matrix',
    value: '\\begin{matrix} a & b \\\\ c & d \\end{matrix}',
    title: '插入 2 x 2 矩阵',
    selectText: 'a',
  },
]

export const MATH_PANEL_TABS: MathPanelTab[] = [
  { id: 'structure', label: '结构' },
  { id: 'operator', label: '运算' },
  { id: 'relation', label: '关系' },
  { id: 'letter', label: '字母' },
  { id: 'set', label: '集合逻辑' },
  { id: 'common', label: '常用' },
]

export const MATH_SYMBOL_GROUPS: Record<Exclude<MathInputPanel, 'structure'>, MathSymbol[]> = {
  operator: [
    { label: '+', value: '+', title: '加号' },
    { label: '-', value: '-', title: '减号' },
    { label: '×', value: '\\times ', title: '乘号' },
    { label: '÷', value: '\\div ', title: '除号' },
    { label: '·', value: '\\cdot ', title: '点乘' },
    { label: '∗', value: '\\ast ', title: '星号运算' },
    { label: '⋆', value: '\\star ', title: '星形运算' },
    { label: '∘', value: '\\circ ', title: '复合运算' },
    { label: '•', value: '\\bullet ', title: '点运算' },
    { label: '±', value: '\\pm ', title: '正负号' },
    { label: '∓', value: '\\mp ', title: '负正号' },
    { label: '⊕', value: '\\oplus ', title: '直和' },
    { label: '⊖', value: '\\ominus ', title: '圆圈减' },
    { label: '⊗', value: '\\otimes ', title: '张量积' },
    { label: '⊘', value: '\\oslash ', title: '圆圈除' },
    { label: '⊙', value: '\\odot ', title: '圆圈点' },
  ],
  relation: [
    { label: '=', value: '=', title: '等于' },
    { label: '≠', value: '\\neq ', title: '不等于' },
    { label: '≈', value: '\\approx ', title: '约等于' },
    { label: '≡', value: '\\equiv ', title: '恒等于' },
    { label: '∼', value: '\\sim ', title: '相似' },
    { label: '≃', value: '\\simeq ', title: '渐近相等' },
    { label: '≅', value: '\\cong ', title: '全等' },
    { label: '∝', value: '\\propto ', title: '正比于' },
    { label: '<', value: '<', title: '小于' },
    { label: '>', value: '>', title: '大于' },
    { label: '≤', value: '\\leq ', title: '小于等于' },
    { label: '≥', value: '\\geq ', title: '大于等于' },
    { label: '≪', value: '\\ll ', title: '远小于' },
    { label: '≫', value: '\\gg ', title: '远大于' },
    { label: '∥', value: '\\parallel ', title: '平行' },
    { label: '⊥', value: '\\perp ', title: '垂直' },
    { label: '∣', value: '\\mid ', title: '整除' },
    { label: '∤', value: '\\nmid ', title: '不整除' },
    { label: '≺', value: '\\prec ', title: '先于' },
    { label: '≻', value: '\\succ ', title: '后于' },
    { label: '≼', value: '\\preceq ', title: '先于或等于' },
    { label: '≽', value: '\\succeq ', title: '后于或等于' },
  ],
  letter: [
    { label: 'α', value: '\\alpha ', title: 'alpha' },
    { label: 'β', value: '\\beta ', title: 'beta' },
    { label: 'γ', value: '\\gamma ', title: 'gamma' },
    { label: 'δ', value: '\\delta ', title: 'delta' },
    { label: 'ε', value: '\\epsilon ', title: 'epsilon' },
    { label: 'ϵ', value: '\\varepsilon ', title: 'varepsilon' },
    { label: 'ζ', value: '\\zeta ', title: 'zeta' },
    { label: 'η', value: '\\eta ', title: 'eta' },
    { label: 'θ', value: '\\theta ', title: 'theta' },
    { label: 'ϑ', value: '\\vartheta ', title: 'vartheta' },
    { label: 'ι', value: '\\iota ', title: 'iota' },
    { label: 'κ', value: '\\kappa ', title: 'kappa' },
    { label: 'λ', value: '\\lambda ', title: 'lambda' },
    { label: 'μ', value: '\\mu ', title: 'mu' },
    { label: 'ν', value: '\\nu ', title: 'nu' },
    { label: 'ξ', value: '\\xi ', title: 'xi' },
    { label: 'π', value: '\\pi ', title: 'pi' },
    { label: 'ϖ', value: '\\varpi ', title: 'varpi' },
    { label: 'ρ', value: '\\rho ', title: 'rho' },
    { label: 'ϱ', value: '\\varrho ', title: 'varrho' },
    { label: 'σ', value: '\\sigma ', title: 'sigma' },
    { label: 'ς', value: '\\varsigma ', title: 'varsigma' },
    { label: 'τ', value: '\\tau ', title: 'tau' },
    { label: 'υ', value: '\\upsilon ', title: 'upsilon' },
    { label: 'φ', value: '\\phi ', title: 'phi' },
    { label: 'ϕ', value: '\\varphi ', title: 'varphi' },
    { label: 'χ', value: '\\chi ', title: 'chi' },
    { label: 'ψ', value: '\\psi ', title: 'psi' },
    { label: 'ω', value: '\\omega ', title: 'omega' },
    { label: 'Γ', value: '\\Gamma ', title: 'Gamma' },
    { label: 'Δ', value: '\\Delta ', title: 'Delta' },
    { label: 'Θ', value: '\\Theta ', title: 'Theta' },
    { label: 'Λ', value: '\\Lambda ', title: 'Lambda' },
    { label: 'Ξ', value: '\\Xi ', title: 'Xi' },
    { label: 'Π', value: '\\Pi ', title: 'Pi' },
    { label: 'Σ', value: '\\Sigma ', title: 'Sigma' },
    { label: 'Υ', value: '\\Upsilon ', title: 'Upsilon' },
    { label: 'Φ', value: '\\Phi ', title: 'Phi' },
    { label: 'Ψ', value: '\\Psi ', title: 'Psi' },
    { label: 'Ω', value: '\\Omega ', title: 'Omega' },
    { label: 'ℓ', value: '\\ell ', title: '手写体 l' },
    { label: 'ℏ', value: '\\hbar ', title: '约化普朗克常数' },
    { label: 'ℜ', value: '\\Re ', title: '实部' },
    { label: 'ℑ', value: '\\Im ', title: '虚部' },
    { label: 'ℵ', value: '\\aleph ', title: '阿列夫数' },
  ],
  set: [
    { label: '∈', value: '\\in ', title: '属于' },
    { label: '∉', value: '\\notin ', title: '不属于' },
    { label: '∋', value: '\\ni ', title: '包含元素' },
    { label: '⊂', value: '\\subset ', title: '真子集' },
    { label: '⊃', value: '\\supset ', title: '真超集' },
    { label: '⊆', value: '\\subseteq ', title: '子集' },
    { label: '⊇', value: '\\supseteq ', title: '超集' },
    { label: '∪', value: '\\cup ', title: '并集' },
    { label: '∩', value: '\\cap ', title: '交集' },
    { label: '∖', value: '\\setminus ', title: '差集' },
    { label: '∅', value: '\\varnothing ', title: '空集' },
    { label: 'ℕ', value: '\\mathbb{N}', title: '自然数集' },
    { label: 'ℤ', value: '\\mathbb{Z}', title: '整数集' },
    { label: 'ℚ', value: '\\mathbb{Q}', title: '有理数集' },
    { label: 'ℝ', value: '\\mathbb{R}', title: '实数集' },
    { label: 'ℂ', value: '\\mathbb{C}', title: '复数集' },
    { label: '∀', value: '\\forall ', title: '任意' },
    { label: '∃', value: '\\exists ', title: '存在' },
    { label: '∄', value: '\\nexists ', title: '不存在' },
    { label: '¬', value: '\\neg ', title: '逻辑非' },
    { label: '∧', value: '\\land ', title: '逻辑与' },
    { label: '∨', value: '\\lor ', title: '逻辑或' },
    { label: '∴', value: '\\therefore ', title: '所以' },
    { label: '∵', value: '\\because ', title: '因为' },
    { label: '⊤', value: '\\top ', title: '真' },
    { label: '⊥', value: '\\bot ', title: '假' },
  ],
  common: [
    { label: '∞', value: '\\infty ', title: '无穷大' },
    { label: '°', value: '^{\\circ}', title: '角度' },
    { label: '∂', value: '\\partial ', title: '偏导数' },
    { label: '∇', value: '\\nabla ', title: '梯度' },
    { label: '∑', value: '\\sum_{i=1}^{n}', title: '求和' },
    { label: '∏', value: '\\prod_{i=1}^{n}', title: '连乘' },
    { label: '∐', value: '\\coprod ', title: '余积' },
    { label: '∫', value: '\\int_{a}^{b}', title: '积分' },
    { label: '∬', value: '\\iint ', title: '二重积分' },
    { label: '∭', value: '\\iiint ', title: '三重积分' },
    { label: '∮', value: '\\oint ', title: '环路积分' },
    { label: 'lim', value: '\\lim_{x \\to a}', title: '极限' },
    { label: '→', value: '\\to ', title: '右箭头' },
    { label: '←', value: '\\leftarrow ', title: '左箭头' },
    { label: '↔', value: '\\leftrightarrow ', title: '双向箭头' },
    { label: '⇒', value: '\\Rightarrow ', title: '推出' },
    { label: '⇔', value: '\\Leftrightarrow ', title: '等价推出' },
    { label: '↦', value: '\\mapsto ', title: '映射到' },
    { label: '↑', value: '\\uparrow ', title: '上箭头' },
    { label: '↓', value: '\\downarrow ', title: '下箭头' },
    { label: '∠', value: '\\angle ', title: '角' },
    { label: '△', value: '\\triangle ', title: '三角形' },
  ],
}
